
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: hr-api-gateway-zuul

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000


zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**